### ISSUE TITLE
issue post deployment of application in service fabric

### ISSUE THREAD

**Issue by Aakanksha345** [Microsoft/SmartHotel360-Registration#3]
I was able to deploy the application locally. But when i try to run the service fabric explorer- i face couple of issues related to health of application.

Number of nodes i can see is only 1.

Image is attached below.

![image](https://user-images.githubusercontent.com/25923578/56965799-b1d22700-6b7b-11e9-9a31-4ec448eea3f8.png)

![image](https://user-images.githubusercontent.com/25923578/56966285-68cea280-6b7c-11e9-986e-6ef1128d1cd6.png)

**Comment by dsanchezcr** [comment]
We won't continue working on Service Fabric for this demo.
